### ISSUE TITLE
node axes in blender

### ISSUE THREAD

**Issue by rafmudaf** [zanoni-mbdyn/blendyn#33]
Hi,

I'm wondering if there is some way to turn off the node axis indicator in Blender. 
![screen shot 2018-04-18 at 4 14 49 pm](https://user-images.githubusercontent.com/13797903/38960992-a94cdcaa-4323-11e8-8184-b3e2d8e24f28.png)

My apologies if this is not a problem but rather due to my lack of knowledge on using Blender.

Thanks
Rafael

**Comment by zanoni-mbdyn** [comment]
Hi Rafael, 
you can import nodes using different objects using the `Import nodes as:` dropdown menu in the `MBDyn nodes` section of the `Scene Properties` panel. You can import them as Arrows, as in this case, just plain axes (without arrows nor X, Y, Z labels), UV Spheres, NURBS Spheres or Cones. 

Depending on what you want to do, there are also other options: for example, you might want to just hide the node's reference frames: you can achieve this by moving the nodes Empty Arrows objects to a different layer: just select them, press `m` and then the box of the layer where you want to move them to. 

Otherwise if the number of nodes in your model is limited, you can also directly assign each of them to a specific object in the Blender scene. To do so, after you have selected MBDyn output file, just select `Load .log file`, in the main Blendyn panel on the left side. Then select the Blender object you want to assign to a node, go to the `Object Properties` panel (right side panel) and scroll down: you'll see an `MBDyn nodes` section that lists all the nodes present in your model. You can hit `ASSIGN` to tie the motion of the selected Blender object to the corresponding node. 

Let me know if this solves your problem. 

Cheers
Andrea

**Comment by zanoni-mbdyn** [comment]
I'm closing this for now.

**Comment by rafmudaf** [comment]
@zanoni-mbdyn my apologies for not responding and I appreciate your help.

Your suggestion of moving the arrows to another layer is exactly what I am looking for. Its a little tedious to do manually but gets the job done.

Do you know of a method for doing this programmatically or automatically? Like a "select all" for arrows?

**Comment by zanoni-mbdyn** [comment]
It is very easy to do it via the Python console. For example for nodes:
```
nodeobjs = [obj for obj in bpy.data.objects if 'node' in obj.name]
for nodeobj in nodeobjs:
    nodeobj.select = True
```
Take care of deselecting everything before doing so :)

Cheers
Andrea
