### ISSUE TITLE
MBDyn standard import in Blendyn

### ISSUE THREAD

**Issue by ghost** [zanoni-mbdyn/blendyn#34]
Hello,

I'm trying to use "MBDyn Standard Import" in order to add all elements to the scene, however I get an error and blendyn stops working as soon as I click on Import Button. In addition, when I'm going to add elements from the scene property panel, for example adding a spherical hinge (or many others), I get the same error and same situation of blendyn!
Btw, I'm using Blender2.76b and mbdyn-1.7.3. Also, here is the error that I get:

```
blender: /build/blender-40PcOX/blender-2.76.b+dfsg0/source/blender/blenlib/intern/math_rotation.c:1328: get_rotation_order_info: Assertion `order >= 0 && order <= 6' failed.
Aborted (core dumped)

```
  
Any idea or help would be great :)

Best, 
Neda

**Comment by zanoni-mbdyn** [comment]
Hi Neda. Thanks for the report. Unfortunately, I'm afraid that is a bug in the specific Blender version you're using. At least, to my understanding that is the case, since it doesn't appear in any other version I've tested Blendyn with. 

Could you please try with a different version downloaded from the [Blender website](https://www.blender.org/download/releases/)? I've added a brief comment in the wiki on how to use your system's Python installation with it. You can find it [here](https://github.com/zanoni-mbdyn/blendyn/wiki/Installation#optional-packages).

Cheers
Z

**Comment by ghost** [comment]
Hi Andrea, 

I tried with Blendyn 2.79 and now it works properly!
Thanks for your comments :)

Best, 
Neda

**Comment by zanoni-mbdyn** [comment]
That's great! :)

Thank you for posting your experience here.
