### ISSUE TITLE
Rotation problem in animation

### ISSUE THREAD

**Issue by ZhangRunsen** [zanoni-mbdyn/blendyn#44]
Hello, everyone.  
I am a new user of blendyn. It looks insteresting to render MBDyn model in blender.   
However, when I tried to render a rotating beam, I find the beam will rotate 360deg (eg. from -180 to 180) druing the rotation, resulting in a flip in the animation, such as the one in the gif.  
Is it about the description of rotation in two softwares?
And do you have any idea to fix it, or any suggestion ?
Thanks,
Best regards, 
Runsen.
![rotation_mode1_withoutpd](https://user-images.githubusercontent.com/48231217/112357999-3417e700-8cd0-11eb-91b1-775fdc00d1ab.gif)

**Comment by zanoni-mbdyn** [comment]
Hi Runsen, nice to hear that you are using Blendyn!

The problem you are experiencing is almost surely due to the rotation parametrization that you are using (i presume it is the default, Euler angles). Try using the orientation vector representation, instead, adding
```
default orientation: orientation vector;
```
to your control data. That should fix your problem.

**Comment by ZhangRunsen** [comment]
Hi,  Andrea,
Thanks for your suggestion. 
Sorry for the late reply, I struggled with blender and the GPU drivers in weekends. 
For the rotation problem, I tried your suggestion, but  I still see the problem at some key frames 
(Btw, I used a released blender2.92/stable from snap now. Although I tried it with different versions, including blender 2.79, 2.83lts, and 2.92, the same problem is observed.)
![rotation_problem](https://user-images.githubusercontent.com/48231217/112854865-8f6e1e80-90ae-11eb-886a-4cd9e77777f2.jpg)
And here is the MBDyn script I used. 
[beam.zip](https://github.com/zanoni-mbdyn/blendyn/files/6222592/beam.zip)

Another problem is that when I quit blender, there seems to be an unregistered problem about the blendyn add-on, as shown in the figure. 
![blender_quit_problem](https://user-images.githubusercontent.com/48231217/112856516-27b8d300-90b0-11eb-8fbf-469bbad1b341.png).

Thanks for your help again, 
Best regards, 
Runsen.

**Comment by zanoni-mbdyn** [comment]
Runsen, thank you for your feedback. As for the latest problem, I had a fix already committed in `devel`, but it had not been merged in `master` yet. Now it should be fine. 

For the first problem, actually I initially misunderstood it for an issue on nodes' rotations, but now inspecting the output myself I get that it is really about the orientations of the beam3 sections... I will investigate further.

**Comment by ZhangRunsen** [comment]
Thanks, Andrea.
Best regards, 
Runsen.

**Comment by zanoni-mbdyn** [comment]
Hi Runsen, I played a little bit more with your model and in the end I think that the problem relies on the way in which Blender handles the curve *twist*, which in turn is related to the tilting of the sections of the curve bevel object (in this case, the NACA profile curve).

I think that the tilt should be really set at each time-step in the animation in a way that is consistent with the beam deformations. However, at the moment I do not have time to implement and test this... We'll see, maybe we can find some willing GSoC student ;)

As an alternative, my advice for you is to try the new, eXperimental feature **components**. Since it is not yet documented, I thought of getting the opportunity and upload a video on YouTube, creating the stub for the Blendyn channel. You can find it [here](https://youtu.be/Oznr3oQPCLc): let me know if it clear enough!

**Comment by zanoni-mbdyn** [comment]
Oh, sorry, I forgot to mention that I also took the opportunity for fixing a couple of bugs here and there. In the video, I use the latest Blendyn version that can be found on the `devel` branch.

**Comment by ZhangRunsen** [comment]
Thanks for your guidance, Andrea. That's helpful to me.
The video is very clear, and I see the procedure to add a new component to beam3 elements.
A little suggestion is that it would be more helpful to beginners if there is narration for operations in the video. 
I will test it soon, and give you feedback.
Happy holidays !
Runsen.

**Comment by ZhangRunsen** [comment]
Thanks, Andrea. 
I tested it following the video, and there is no problem about the rotation.

Happy holidays!
Runsen.

**Comment by zanoni-mbdyn** [comment]
Thank you for trying it out, Runsen. 

And yes you are right, commentary would be useful in the videos.I did this one very quickly and I did not manage to record also the audio. The future ones will be the compete package!

**Comment by zanoni-mbdyn** [comment]
Oh, and happy holidays to you, too ;)
