### ISSUE TITLE
Aerodynamic beam3 visualization problem

### ISSUE THREAD

**Issue by libo663** [zanoni-mbdyn/blendyn#58]
When modeling a twisted blade, the aerodynamic beam3 element was well defined, but in Blendyn it didn't twist as expected.
![image](https://github.com/zanoni-mbdyn/blendyn/assets/37033487/b4c7d966-c3de-4f4e-8c64-90140fbf2b71)
![image](https://github.com/zanoni-mbdyn/blendyn/assets/37033487/ac01efcf-b2e8-45fa-9385-49737f0c8867)

**Comment by zanoni-mbdyn** [comment]
Hi @libo663, the problem was in how the `.log` file entry of `aerodynamic beam2` and `aerodynamic beam3` elements was written (incorrectly) in MBDyn. With [this fix](https://public.gitlab.polimi.it/DAER/mbdyn/-/merge_requests/161) the problem should be fixed (test case follows).

```C++
c81 data: (integer NACA0012 = 12), "../../var/naca0012.c81";
	set: const real ALPHA = 0.;
	set: const real TWIST075 = 7.*deg2rad;
	aerodynamic beam3: 2, 2,
		reference, node, null,
		reference, node,
			1, 0., cos(ALPHA), sin(ALPHA),
			3, 1., 0., 0.,
		reference, node, null,
		reference, node,
			1, 0., cos(ALPHA), sin(ALPHA),
			3, 1., 0., 0.,
		reference, node, null,
		reference, node,
			1, 0., cos(ALPHA), sin(ALPHA),
			3, 1., 0., 0.,
		const, R/15.,
		const, 0.,
		const, 0.,
		linear, .75*TWIST075, -0.25*TWIST075,
		3,
		c81, NACA0012, jacobian, yes;
```
![image](https://github.com/zanoni-mbdyn/blendyn/assets/7814088/eb1c4db3-aeb1-4778-9c02-4c9adbe3a05c)

**Comment by libo663** [comment]
Hi @zanoni-mbdyn . Thank you for fixing this problem, I will try it later.
